---
- name: Role nginx | install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
# - name: Role nginx | create document root
#   ansible.builtin.file:
#     path: '{{ sites_path }}'
#     state: directory
#     owner: 'www-data'
#     group: 'www-data'
#     mode: '0755'

# - name: Role nginx | remove default page
#   ansible.builtin.file:
#     state: absent
#     path: /etc/nginx/sites-enabled/default

# - name: Role nginx | start service
#   ansible.builtin.service:
#     name: nginx
#     state: started
#     enabled: true
