---
- name: Install datablese
  become: true
  hosts: db
  roles:
    - mysql

- name: Install php
  become: true
  hosts: php
  roles:
    - php

- name: Install nginx and wordpress
  become: true
  hosts: nginx
  roles:
    - nginx
    - wordpress
