---
- name: Load variables
  hosts: all
  tasks:
    - name: Load vars
      ansible.builtin.include_vars:
        file: '{{ playbook_dir }}/vars/default.yml'

- name: Install datablese
  become: true
  hosts: db
  roles:
    - mysql

- name: Install php
  become: true
  hosts: php
  roles:
    - php

- name: Install nginx and wordpress
  become: true
  hosts: nginx
  roles:
    - nginx
    - wordpress
