---
- name: Role mysql | install mariadb
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3
      - python3-pip
    update_cache: true
    state: present

- name: Role mysql | install pymysql using pip
  ansible.builtin.pip:
    name: pymysql
    state: present
    executable: pip3

- name: Role mysql | Started mariadb service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Role mysql | Set the root password
  community.mysql.mysql_user:
    name: root
    password: '{{ root_password }}'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: '{{ root_password }}'

- name: Role mysql | remove anonymous user accounts
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: '{{ root_password }}'
  no_log: true

- name: Role mysql | remove the MySQL test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: '{{ root_password }}'

- name: Role mysql | create database
  community.mysql.mysql_db:
    name: '{{ db_name }}'
    state: present
    login_user: root
    login_password: '{{ root_password }}'

- name: Role mysql | create MySQL admin user for database
  community.mysql.mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_pass }}'
    priv: '{{ db_name }}.*:ALL'
    state: present
    login_user: root
    login_password: '{{ root_password }}'
