---
YNDX:
  vars:
    ansible_user: ansible
    ansible_port: 22
    ansible_ssh_private_key_file: '{{ inventory_dir }}/group_vars/id_ed25519'
  hosts:
    db:
      ansible_host: 62.84.120.94
    nginx:
      ansible_host: 62.84.120.94
    php:
      ansible_host: 62.84.120.94
